chotuve-grupo10/chotuve-application-server

app_server/docs/about.yml
app_server/docs/home.yml

- Arreglamos el bug que hacía que no anduviese Swagger.

Fix bug de Swagger

---

.pylintrc
.travis.yml
app_server/__init__.py
app_server/authentication.py
app_server/docs/register.yml
app_server/http_functions.py

- Fachada del app server para consumir endpoint de auth server de registro de usuario. Ahora podemos registrar un user desde el app server.
- Closes #26

Registro user password

---

.pylintrc
.travis.yml
app_server/authentication.py
app_server/docs/login.yml
app_server/docs/validate_token.yml
app_server/http_functions.py
app_server/token_functions.py
setup.py

- Login desde app server. Se hace validación de credenciales con auth server
- Si las credenciales son correctas también se genera un token desde el app server para las acciones relacionadas con este.
- También se creó un endpoint para validar el token generado por el app server

Login user password

---

.travis.yml
app_server/__init__.py
app_server/authentication.py
app_server/docs/login_with_facebook.yml
app_server/docs/login_with_firebase.yml
app_server/docs/login_with_google.yml
app_server/docs/register.yml
app_server/docs/register_with_facebook.yml
app_server/docs/register_with_firebase.yml
app_server/docs/register_with_google.yml
app_server/docs/validate_auth_token.yml
app_server/http_functions.py
tests/test_app_server.py
tests/test_http_functions.py

- Implementación de registro y login de firebase.

Register login firebase

---

app_server/docs/login.yml

Agrego schema de respuesta en /login para que funcione bien el generador de código de Android

Corrección menor en documentación

---

README.md
app_server/docs/list_videos.yml
app_server/docs/list_videos_for_user_id.yml

- El PM @nicolaslongo dejó las definiciones correctas en swagger para los listados de videos. 
- Yo simplemente agregué el comando de docker al readme porque paja armarlo todo los días

Fix swagger definitions

---

app_server/videos.py
tests/test_videos.py

Al final, un array compuesto por documentos es formato json.
Mucho más straightforward

Modifico la estructura de response de list Videos

---

app_server/rules.py
requirements.txt
tests/test_rules.py

No tiene nada de comportamiento pero quiero avanzar con otra cosa

Durable rules

---

app_server/docs/friendship_request.yml
app_server/docs/friendship_response.yml
app_server/docs/get_users_by_query.yml
app_server/users.py

- fix de un parametro que para swagger iba por path pero en realidad era de tipo QUERY (tambien por parametro)

Filtrar users query

---

Dockerfile
app_server/http_functions.py
app_server/users_db_functions.py
tests/test_users_db_functions.py

- Usamos header para que el auth server nos deje pasar

App server token para auth server

---

app_server/authentication.py

- fix del fix del fix del fix una rosa es una rosa

Fix del fix del fix de login with firebase

---

Dockerfile
app_server/http_functions.py

- Se agrega el header AppServerToken para que el media server valide que conoce al server que le está hablando.

Uso de media server token

---

app_server/docs/get_user_requests.yml
app_server/users.py
app_server/users_db_functions.py
tests/test_users_db_functions.py

- listar requests de amistad para mostrarlas en Android

Listar requests

---

app_server/__init__.py
app_server/docs/add_notifications_token_to_user.yml
app_server/docs/assign_notifications_token_to_user.yml
app_server/push_notifications.py
tests/test_push_notifications.py

- servicio que permite agregar un FirebaseId a un usuario en particular

Add firebase id token para push notifications

---

Dockerfile
app_server/push_notifications.py
app_server/relationships_functions.py
app_server/utils/notification_messages.py
tests/test_push_notifications.py
tests/test_relationships_functions.py
tests/test_users_db_functions.py

Envío push notifications a los usuarios cuando:
- alguien le envia una solicitud de amistad
- alguien acepta su solicitud de amistad

Send push notifications

---

app_server/__init__.py
app_server/docs/get_server_time.yml
app_server/time.py

- GET url que devuelve el ServerTime de la timezone de Argentina

Server date time

---

app_server/docs/delete_dislike_to_video.yml
app_server/docs/delete_like_to_video.yml
app_server/docs/dislike_video.yml
app_server/docs/like_video.yml
app_server/docs/reset_password.yml
app_server/push_notifications.py
app_server/users_db_functions.py

- algunos fixes de swagger
- fix de respuestas cuando le pegas con el mismo token a un usuario que ya lo tenía

Fixes swagger reactions

---

app_server/docs/list_videos_of_user.yml
app_server/videos.py
app_server/videos_db_functions.py
tests/test_videos.py
tests/test_videos_db_functions.py

- Se listan videos de un usuario dependiendo de si el usuario que lo solicita es amigo o no.
- Se tiene en cuenta que el usuario sea uno mismo.

Listar videos de un usuario

---

app_server/docs/comment_video.yml
app_server/time.py
app_server/videos.py
app_server/videos_db_functions.py
tests/test_videos.py
tests/test_videos_db_functions.py

- Improve a la logica de comentarios

Agrego modificaciones a la logica, swagger y nuevos tests

---

app_server/docs/modify_user_profile.yml
app_server/users.py
tests/test_users.py

- Endpoint para modificar el perfil de un user. Chequeamos que no se quiera modificar el perfil de otra persona (no da)

Modificar perfil

---

tests/test_authentication.py
tests/test_push_notifications.py
tests/test_videos_db_functions.py
tests/test_videos_reactions.py

- Llegamos a 75% de cobertura. Now we need a nap

Cobertura tests

---

README.md

Mejorar readme
